# Site settings
title: Shailesh Kumar Sahu
description: >- # this means to ignore newlines until "baseurl:"
  I don't want to proove anything.
  I just know that when you achieve
  something big. Every sentence out
  of your mouth seems like a Quote.
baseurl: ""  # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
repository: YoussefRaafatNasry/portfolYOU
remote_theme: YoussefRaafatNasry/portfolYOU

# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed


# Author Info
author:
  name     : John Doe
  image    : https://i2.cdn.turner.com/cnnnext/dam/assets/140926165711-john-sutter-profile-image-large-169.jpg
  email    : username@xyz.com
  github   : username
  twitter  : username
  linkedin : username
  facebook : username


# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


# Posts default Permalink
permalink: articles/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock