# Site settings
title: Shailesh Kumar Sahu
description: >- # this means to ignore newlines until "baseurl:"
  I don't want to proove anything.
  I just know that when you achieve
  something big. Every sentence out
  of your mouth seems like a Quote.
baseurl: ""  # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
repository: YoussefRaafatNasry/portfolYOU
remote_theme: YoussefRaafatNasry/portfolYOU

# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed


# Author Info
author:
  name     : Shailesh Kumar Sahu
  image    : https://user-images.githubusercontent.com/36515927/57946981-4ae29b00-78fb-11e9-9159-abe920b00be5.jpg
  email    : shaileshkumar2604@gmail.com 
  github   : shellkore
  twitter  : ShellKoreSahu
  linkedin : shellkore
  facebook : shellkore


# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


# Posts default Permalink
permalink: articles/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock